### ISSUE TITLE
Add Documentation on Micro Integrator CLI

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-mi#100]
**Description:**
$subject

**Reference:**
[Feature doc](https://docs.google.com/document/d/1VCWbiU6CKT7W1lcTCPaEaERZftWF2oxM4j22Xxs4DQ0/edit)

**Comment by SanojPunchihewa** [comment]
Fixed with https://github.com/wso2/docs-mi/pull/433. MI CLI was released with MI 4.3.0. We should use apictl with MI 4.2.0. Hence removing the 4.2.0 label as well
