### ISSUE TITLE
Documentation changes needed for tutorials

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#1007]
## Description
Lab 7 : https://apim.docs.wso2.com/en/4.0.0/tutorials/integration-tutorials/routing-requests-based-on-message-content/

- As informed earlier if these labs can have unique names instead of SampleServices, it helps in mitigating weird errors and confusion that we come across while doing many labs with the same name. Vinod is aware of weird issues we faced during the training.
- New Integration Project dialog box screenshot is incorrect as Registry Resource and Connector Exporter projects are also ticked.
- When configuring the API Resource, there is a dot at the end of the URI TEMPLATE value ( Point 4 in Create a REST API section ) as /categories/{category}/reserve. To avoid unexpected mistakes while copying the URI TEMPLATE value from docs, it would be great to remove the dot at the end.
- Same issue in the Log mediator inside the switch case. Expression of the log mediator has a dot at the end fn:concat('Routing to ', get-property('Hospital')).

 

Lab 8 : https://apim.docs.wso2.com/en/4.0.0/tutorials/integration-tutorials/transforming-message-content/

- Same as Lab 7, good if name can be made unique.
- Same as Lab 7, New Integration Project dialog box screenshot is incorrect.

 

Lab 9 : https://apim.docs.wso2.com/en/4.0.0/tutorials/integration-tutorials/exposing-several-services-as-a-single-service/

- Same as above two labs, name needs to be made unique.
- Same as above two labs, screenshot of New Integration Project dialog box is incorrect.
- Same as Lab 7, remove the dot at the end of the URI TEMPLATE of  API Resource /categories/{category}/reserve.
- In the “Update the mediation flow” section in the point 1 it says “You will see the canvas for the in sequence and out sequence as shown below. “, but no screenshot is available.
- In the point 2 of the same, it asks to name the property as Get Hospital (“name it Get Hospital.”). But actually property should be named as uri.var.hospital and it is mentioned correctly in the table below above statement. Get Hospital may be to give as the description of the property.
- Same for card_number property, doc says to name it as Get Card Numbe. (“name it Get Card Number.”) which is incorrect.
- In the “Update the Mediation Flow” section in the point no 5, json path expression for card_number property is incorrect. It should be json-eval($.patient.cardNo) instead of json-eval($.cardNo)
- In the “Update the Mediation Flow” section in the point no 16, there’s again a misleading dot at the end of first expression of payload factory mediator ($ctx:uri.var.appointment_id.)

 

Apart from the above 3 labs, there were issues noticed in other labs as well. Appreciate it if all these issues can be fixed at your earliest as these cause dis-satisfaction for a novice user when trying out these labs in integration studio for the first time.

Lab 10 : https://apim.docs.wso2.com/en/4.0.0/tutorials/integration-tutorials/using-templates/

- New Integration Project dialog box screenshot is incorrect as Registry Resource and Connector Exporter projects are also ticked.
- Same as previous labs, good if name (SampleServices ) can be made unique.
- When configuring the API Resource, there is a dot at the end of the URI TEMPLATE value ( Point 4 in Create a REST API section ) as /categories/{category}/reserve. To avoid unexpected mistakes while copying the URI TEMPLATE value from docs, it would be great to remove the dot at the end.
- Under step 5: Testing the usecase, provided request payload is incorrect and should be replaced with the below payload.

```
{

    "patient": {

    "name": "John Doe",

    "dob": "1940-03-19",

    "ssn": "234-23-525",

    "address": "California",

    "phone": "8770586755",

    "email": [johndoe@gmail.com](mailto:johndoe@gmail.com)

    },

    "doctor": "thomas collins",

    "hospital_id": "grandoaks",

    "hospital": "grand oak community hospital",

    "appointment_date": "2025-04-02"

}
```

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Reopening this issue since it was closed automatically upon merging the PR. Please verify the fixes and close the isse.

**Comment by chanikag** [comment]
Adding unique project names for tutorials will be handled by the issue https://github.com/wso2/docs-mi/issues/993
Other issues are fixed now.
