### ISSUE TITLE
[Tutorials] Add links for artifact types

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#1015]
## Description
For example in [1] REST APIs, Mediators are not linked to the relevant content. It is better to link those.

[1] https://mi.docs.wso2.com/en/latest/learn/integration-tutorials/sending-a-simple-message-to-a-service/

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Reopening this issue since it was closed automatically upon merging the PR. Please verify the fixes and close the issue.
