### ISSUE TITLE
Create GitHub Action to automate PR creation for main branch

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-mi#1017]
**Description:**

We need to create a GitHub Action that automates the following process:

When a PR is sent to the `4.3.0` branch [1], the same changes should automatically trigger the creation of a PR to the `main` branch [2].
The PR to the `main` branch should not be merged automatically. It will remain open for review and approval by a reviewer.

[1] https://github.com/wso2/docs-mi/tree/4.3.0
[2] https://github.com/wso2/docs-mi/tree/main

**Comment by chanikag** [comment]
PR: https://github.com/wso2/docs-mi/pull/1054
