### ISSUE TITLE
No content on the link https://mi.docs.wso2.com/en/latest/reference/synapse-properties/sequence-properties/

### ISSUE THREAD

**Issue by lianescafarate** [wso2/docs-mi#103]
**Description:**

When I click on this link: https://mi.docs.wso2.com/en/latest/reference/synapse-properties/sequence-properties/ there's no available content

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by DinithiDiaz** [comment]
Hi @lianescafarate, 

Thanks for reporting! The Mediation Sequences document has been added via the above-linked PRs, and you can access it from [here](https://mi.docs.wso2.com/en/latest/reference/mediation-sequences/).

Thanks & Kind Regards,
Dinithi
