### ISSUE TITLE
Replace subtitle "Types of connectors"

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/docs-mi#1030]
**Description:**

There are no connector types. Instead of "Types of connectors" at [1], we can use "Different categories of connectors". We need to update other applicable places as well.

[1] - https://apim.docs.wso2.com/en/4.2.0/reference/connectors/connectors-overview/#types-of-connectors

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
PR https://github.com/wso2/docs-mi/pull/1038

**Comment by DinithiDiaz** [comment]
Reopening this issue since it was closed automatically upon merging a PR. Please verify the fixes and close the issue.
