### ISSUE TITLE
"Using Wire Logs" page cannot be found

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/docs-mi#1031]
**Description:**

The "Using Wire Logs" page appears in the search results, but it redirects when clicked. We need to retrieve this content from the MI 4.2.0 documentation [1] and update it for the MI 4.3.0 version.

[1] - https://apim.docs.wso2.com/en/4.2.0/integrate/develop/using-wire-logs/

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
PR https://github.com/wso2/docs-mi/pull/1034
