### ISSUE TITLE
Add an example of batch request with Rest Resource and Json Payload for DSS

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-mi#1043]
**Description:**
On [this page](https://mi.docs.wso2.com/en/latest/learn/examples/data-integration/batch-requesting/) only the SOAP interface is described for DSS service batch operations. 

It would be nice to have an example of the same invocation but with a "resource" rather than an "operation". 

In the Restful API invocation, it should be highligthed that the resource in the endpoint URL for a batch invocation should be suffixed with **_batch_req** (i.e. http://localhost:8280/services/JSONSample/employee_batch_req ) otherwise you get the cryptic error message described in [this issue](https://github.com/wso2/product-ei/issues/2372).

**Suggested Labels:**
Area/Examples

**Suggested Assignees:**
[chanikag](https://github.com/chanikag)

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
See related issue

**Related Issues:**
https://github.com/wso2/product-ei/issues/2372

**Comment by chanikag** [comment]
PR: https://github.com/wso2/docs-mi/pull/1062
