### ISSUE TITLE
Wrong example for sequence template mandatory parameters

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-mi#1074]
### Description

In the [example](https://mi.docs.wso2.com/en/latest/learn/examples/template-examples/using-sequence-templates/#synapse-configuration_1) for using mandatory Sequence Template parameters, there's written: 

> According to the sequence template, a value for the greeting message is mandatory.

but in the "greeting_message" parameter definition, the "isMandatory" attribute is set to "false" making it an **optional** parameter. 

### Steps to Reproduce

Read the referenced documentation.

### Version

latest

**Comment by chanikag** [comment]
PR https://github.com/wso2/docs-mi/pull/1136
