### ISSUE TITLE
Add a broken link checker tool

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-mi#278]
**Description:**
Need to add a broken link checker tool to the MI doc space.

**Comment by DinithiDiaz** [comment]
Closing as duplicate; will be tracked via https://github.com/wso2/docs-mi/issues/810.

**Comment by anupama-pathirage** [comment]
@DinithiDiaz usual practice is to keep the old issue while closing the latest issue when it comes to duplicates. Hence re-opening this one.

**Comment by sm1990** [comment]
@anupama-pathirage & @DinithiDiaz The current [mi-docs](https://mi.docs.wso2.com/en/latest/) site doesn't have the meta tags (`<meta name="robots" content="index">` and `<meta name="googlebot" content="index">`) and a robots.txt which allows the crawlers to find the sitemap and crawl through the URLs listed there. This is a major impact on SEO as well. 

I've written, and tested a crawler which worked well with the [ballerina.io](https://ballerina.io/) in which we have implemented all of the above.

**Comment by DinithiDiaz** [comment]
> @anupama-pathirage & @DinithiDiaz The current [mi-docs](https://mi.docs.wso2.com/en/latest/) site doesn't have the meta tags (`<meta name="robots" content="index">` and `<meta name="googlebot" content="index">`) and a robots.txt which allows the crawlers to find the sitemap and crawl through the URLs listed there. This is a major impact on SEO as well.
> 
> I've written, and tested a crawler which worked well with the [ballerina.io](https://ballerina.io/) in which we have implemented all of the above.


Hi all,

I did a bit of research on this sometime back, and from what I understood, since this is a MkDocs site, we can use the `<robots>` property in the `base.html` file of our documentation sites instead of having a separate `robots.txt` file.

**Reference:**
[MkDocs Material documentation](https://squidfunk.github.io/mkdocs-material/reference/?h=robots#using-metadata-in-templates)

According to below resources we only need to add the `<robots>` meta tag if we want to specifically request `noindex` and `nofollow`. Otherwise, it's not necessary to include them.

**Reference:**
[Google Search Central](https://developers.google.com/search/docs/crawling-indexing/special-tags)
[Semrush Blog](https://www.semrush.com/blog/robots-meta/#default-content-values)
