### ISSUE TITLE
Getting Page Not Found Error

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/docs-mi#291]
**Description:**
When clicking on `Developing Your First Integration Solution Using MI for VS Code` in [install-wso2-mi-for-vscode page](https://mi.docs.wso2.com/en/latest/develop/mi-for-vscode/install-wso2-mi-for-vscode/), Getting a PNF error.

<img width="1033" alt="Screenshot 2024-06-25 at 12 27 27" src="https://github.com/wso2/docs-mi/assets/12771261/6bd55e76-0806-4fa7-9d7f-f0ed8e69d458">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by DinithiDiaz** [comment]
Hi,
This is fixed now. Therefore, I will close the issue.

Thanks & Regards,
Dinithi
