### ISSUE TITLE
Tasks related to 4.3.0 doc release

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-mi#304]
## Description
Created this issue to track the tasks related to the MI 4.3.0 doc release.

Reference: [MI 4.3.0 Doc Release Checklist](https://docs.google.com/spreadsheets/d/1mXnEQzYr9o8NQHr4oRzHjtTfMAaiDs90W50ovQ8xRa8/edit?gid=0#gid=0)

**Comment by anupama-pathirage** [comment]
@DinithiDiaz are we done with these tasks?

**Comment by DinithiDiaz** [comment]
Closing this issue since the release-related tasks are completed. The remaining tasks will be tracked by separate doc issues.
