### ISSUE TITLE
Update the downloadable project with the new project structure

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/docs-mi#357]
## Description
> The pre-packaged project in the document [1] needs to be updated with a project that is in accordance with the new project structure that is being used in the VS Code extension.

[1] https://mi.docs.wso2.com/en/4.3.0/mi-analytics/setting-up-mi-analytics/#step-24-optionally-enable-statistics-for-specific-artifacts

<img width="988" alt="Screenshot 2024-07-04 at 13 12 06" src="https://github.com/wso2/docs-mi/assets/37581983/a280708c-da76-4d40-8db8-99f5c183d60d">

**Comment by SanojPunchihewa** [comment]
Since EI analytics is deprecated, the EI Analytics download steps in the above doc are obsolete. Refer https://github.com/wso2-enterprise/wso2-mi-internal/issues/935#issuecomment-2268198284. We will need a complete rewamp of this doc.

**Comment by chanikag** [comment]
Let's remove EI analytics related docs as that is deprecated.
