### ISSUE TITLE
Backend service not provided in the point to point Rabbitmq documentation

### ISSUE THREAD

**Issue by ShammiL** [wso2/docs-mi#390]
## Description
>The [documentation](https://mi.docs.wso2.com/en/4.3.0/learn/examples/rabbitmq-examples/point-to-point-rabbitmq/) on "Point to point RabbitMQ" has a consumer that tries to call a backend `http://localhost:8280/employees`. But the documentation does not provide instructions on how to setup the backend service on port `8280`.

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by GDLMadushanka** [comment]
Fixed in https://github.com/wso2/docs-mi/pull/1104
