### ISSUE TITLE
Update creating a REST API doc

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-mi#406]
## Description
Created this issue to track the changes for creating a REST API feature for the MI VS Code extension.

Page to be updated: https://mi.docs.wso2.com/en/4.3.0/develop/creating-artifacts/creating-an-api/

Related Product issue/issues: 

- https://github.com/wso2/mi-vscode/issues/70
- https://github.com/wso2/mi-vscode/issues/71
- https://github.com/wso2/mi-vscode/issues/61

**Comment by DinithiDiaz** [comment]
The **updating metadata** section has been removed temporarily. Update the content once this feature is implemented properly.

**Comment by SanojPunchihewa** [comment]
This feature is not implemented yet in VSCode plugin. Hence adding the `Furture` milestone. Once the feature is completed, the developer can update the docs accordingly.

**Comment by SanojPunchihewa** [comment]
> The **updating metadata** section has been removed temporarily. Update the content once this feature is implemented properly.

Since we can derive the metadata need for the service catalog, we have improved the CAR plugin to generate them during project building via https://github.com/wso2/maven-tools/pull/135. Hence we don't need to have this **updating metadata** section anymore.

**Comment by SanojPunchihewa** [comment]
We have updated the Integration first approach via https://mi.docs.wso2.com/en/latest/learn/integration-tutorials/service-catalog-tutorial/. Once the API first approach is implemented in MI VSCode plugin we can fix https://github.com/wso2/mi-vscode/issues/71

**Comment by chanikag** [comment]
As the VS code plugin capabilities are not available yet, resolving this issue.
