### ISSUE TITLE
[DOC] Add details about parameter listener.secured_wsdl_epr_prefix 

### ISSUE THREAD

**Issue by isurul28** [wso2/docs-mi#466]
1**Description:**
According to the document[1] we can see  listener.wsdl_epr_prefix parameter for http details under the HTTP/S transport (non-blocking mode) section. 
But there are no mentioned of istener.secured_wsdl_epr_prefix paramter for https.
Please check and update the document accordingly
[1].https://ei.docs.wso2.com/en/latest/micro-integrator/references/config-catalog/#https-transport-non-blocking-mode

**Suggested Labels:**
doc

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/docs-mi/pull/953
