### ISSUE TITLE
Write reference guide document for Salesforce Inbound Endpoint 

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/docs-mi#472]
**Description:**

- Write reference guide document for Salesforce Inbound Endpoint .

**Comment by DinithiDiaz** [comment]
Closing this issue as this page is available in the latest MI documentation: [Salesforce Inbound Endpoint Reference](https://mi.docs.wso2.com/en/latest/reference/connectors/salesforce-connectors/sf-inbound-endpoint-reference-configuration/#salesforce-inbound-endpoint-reference)
