### ISSUE TITLE
Write documentation for Salesforce Inbound Endpoint

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/docs-mi#473]
**Description:**
Write documentation for Salesforce Inbound Endpoint

- Salesforce Inbound Endpoint example.
- Salesforce Inbound Endpoint-configuration doc.

**Comment by arunans23** [comment]
We have docs for SF Inbound endpoint now. https://mi.docs.wso2.com/en/latest/reference/connectors/salesforce-connectors/sf-inbound-endpoint-reference-configuration/
