### ISSUE TITLE
Write a document for FHIR Connector 

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/docs-mi#485]
**Description:**

1. Reefer the configurations and test the FHIR connector.
2. Write a document for FHIR connector configuration and a sample scenario.

**Comment by DinithiDiaz** [comment]
This is already available in the doc space:

- [FHIR Overview](https://mi.docs.wso2.com/en/latest/reference/connectors/fhir-connector/fhir-connector-overview/)
- [FHIR Example](https://mi.docs.wso2.com/en/latest/reference/connectors/fhir-connector/fhir-connector-example/)
- [FHIR Reference](https://mi.docs.wso2.com/en/latest/reference/connectors/fhir-connector/fhir-connector-config/)
