### ISSUE TITLE
Add documentation to Ceridian Dayforce Connector

### ISSUE THREAD

**Issue by abeykoon** [wso2/docs-mi#486]
**Description:**

Add documentation for Ceridian Dayforce Connector

1. A reference guide - methods and parameters
2. A setting up environment guide - get credentials from `Ceridian Dayforce`. How to usetup users etc. 
3. A scenario - a practical scenario using the connector with configs. Use developer studio. Attach screenshots. Attach the Studio project as well.

**Comment by DinithiDiaz** [comment]
This is already available in the doc space.

- [Ceridian Dayforce Overview](https://mi.docs.wso2.com/en/latest/reference/connectors/ceridiandayforce-connector/cerediandayforce-overview/)
- [Set up the Ceridian Dayforce Connector](https://mi.docs.wso2.com/en/latest/reference/connectors/ceridiandayforce-connector/ceridiandayforce-connector-config/)
- [Ceridian Dayforce Example](https://mi.docs.wso2.com/en/latest/reference/connectors/ceridiandayforce-connector/ceridiandayforce-connector-example/)
- [Ceridian Dayforce Reference](https://mi.docs.wso2.com/en/latest/reference/connectors/ceridiandayforce-connector/ceridiandayforce-connector-reference/)
