### ISSUE TITLE
FHIR connector doc improvements 

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/docs-mi#487]
**Description:**
The following message builder should be added to EI/MI axis.xml configuring FHIR configurations. 

``<messageBuilder contentType="application/fhir+json"                                              
                  class="org.wso2.carbon.integrator.core.json.JsonStreamBuilder"/>``

**Affected Product Version:**
All EI/MI products

**Comment by arunans23** [comment]
This is already present in https://mi.docs.wso2.com/en/latest/reference/connectors/fhir-connector/fhir-connector-example/
