### ISSUE TITLE
Fix formatting issues in doc space

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-mi#51]
**Description:**
Need to fix the following formatting issues:

- [ ] Issues caused due to the upgrade of the MkDocs and associated plugins/extensions.
- [ ] Existing formatting issues identified in the doc space.

**Comment by anupama-pathirage** [comment]
@DinithiDiaz Do we know the scope of this work like the pages to be updated etc?

**Comment by DinithiDiaz** [comment]
Update: The formatting issues in the 4.3.0 doc space are fixed via the above-linked PRs. Need to address the issues in the 4.2.0 doc space.

**Comment by DinithiDiaz** [comment]
The formatting issues in the 4.3.0 and 4.2.0 doc spaces have been addressed through the PRs linked above. Therefore, I'm closing this issue.
