### ISSUE TITLE
Add Service catalog content 

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#515]
## Description
The existing content is removed with [1], but when the feature is back as in [2], we need to bring back the revised content.

[1] https://github.com/wso2/docs-mi/pull/514
[2] https://github.com/wso2/mi-vscode/issues/61

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Note: Once the feature is developed, remove the redirections set via https://github.com/wso2/docs-mi/pull/528/.

**Comment by chanikag** [comment]
Closing as the feature is not ready yet and the docs will be added as mentioned in  https://github.com/wso2/mi-vscode/issues/332
