### ISSUE TITLE
Removed AI data mapper from the documentation. 

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/docs-mi#571]
## Description
> Due to the AI data mapper not yet being implemented in the VS Code extension, it has been removed from the this page. https://mi.docs.wso2.com/en/4.3.0/learn/integration-tutorials/transforming-message-content/. 
After it is implemented, it should be added back to the documentation.

**Comment by YasanPunch** [comment]
AI Data Mapper was implemented in VS Code extension, and documentation was added and updated. 
[AI Data Mapper Feature PR](https://github.com/wso2-enterprise/vscode-extensions/pull/3534)
[Documentation PR](https://github.com/wso2/docs-mi/pull/968)
