### ISSUE TITLE
ISO8583 Inbound example doc is outdated

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-mi#650]
## Description

We have introduced a new VSCode UI schema for ISO8583 inbound endpoint. But the current doc[1] contains old UI and configuration steps.

[1] - https://mi.docs.wso2.com/en/latest/reference/connectors/iso8583-connector/iso8583-inbound-endpoint-example/

**Comment by DinithiDiaz** [comment]
PRs: 

- https://github.com/wso2/docs-mi/pull/1180
- https://github.com/wso2/docs-mi/pull/1191

**Comment by DinithiDiaz** [comment]
Closing as fixed.
