### ISSUE TITLE
Some tutorial pages include a video explaining how to send a request from Postman. This video can be removed.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/docs-mi#651]
## Description
Pages identified with a video explaining how to send a Postman request is listed down below. 
* [Send a Simple Message to a Service](https://mi.docs.wso2.com/en/4.2.0/learn/integration-tutorials/sending-a-simple-message-to-a-service/)
* [Routing Requests based on Message Content](https://mi.docs.wso2.com/en/4.2.0/learn/integration-tutorials/routing-requests-based-on-message-content/)
* [Translate Message Formats](https://mi.docs.wso2.com/en/4.2.0/learn/integration-tutorials/transforming-message-content/)
* [Store and Forward Messages for Guaranteed Delivery](https://mi.docs.wso2.com/en/4.2.0/learn/integration-tutorials/storing-and-forwarding-messages/)
* [Send Emails from an Integration Service](https://mi.docs.wso2.com/en/4.2.0/learn/integration-tutorials/using-the-gmail-connector/)
* [Use Inbound Endpoints](https://mi.docs.wso2.com/en/4.2.0/learn/integration-tutorials/using-inbound-endpoints/)
* [Reuse Mediation Sequences](https://mi.docs.wso2.com/en/4.2.0/learn/integration-tutorials/using-templates/)

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by sajinieKavindya** [comment]
This is fixed in 4.3.0 docs.
