### ISSUE TITLE
Update the 'Apply Security to a Proxy Service' guide with the graphical view of policy files

### ISSUE THREAD

**Issue by gabilang** [wso2/docs-mi#658]
## Description
> $Subject

Currently, graphical view of policy files are not supported in the mi-vscode. This feature is under development and being tracked via https://github.com/wso2/mi-vscode/issues/83. Once this feature is live, the [Apply Security to a Proxy Service](https://mi.docs.wso2.com/en/latest/develop/advanced-development/applying-security-to-a-proxy-service/) page needs to be updated with enabling security policies via graphical view contents. 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by rosensilva** [comment]
This depends on the proxy service security feature in vs code

**Comment by chanikag** [comment]
Resolving the issue since the feature https://github.com/wso2/mi-vscode/issues/83 is not yet available.
