### ISSUE TITLE
Update 'Creating an Inbound Endpoint' doc content

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/docs-mi#669]
Content of the 'Creating an Inbound Endpoint' [1] document is outdated as it has configuration steps to guide a user to use the Integration Studio. But this must be updated with the steps that include how this could be achieved via the MI VS Code plugin.

[1] https://mi.docs.wso2.com/en/latest/develop/creating-artifacts/creating-an-inbound-endpoint/

**Comment by DinithiDiaz** [comment]
Closing as duplicate. Will be tracked via https://github.com/wso2/docs-mi/issues/408.
