### ISSUE TITLE
Gmail Connector - Need to create the Github documentation

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#702]
Moving the issue https://github.com/wso2-extensions/esb-connector-gmail/issues/45

![image](https://github.com/user-attachments/assets/4b0b94e0-dbfa-41ac-87fc-3c7d54f5f2ea)

**Comment by DinithiDiaz** [comment]
The Gmail connector documentation has been added to the MI documentation space.

- [Gmail Overview](https://mi.docs.wso2.com/en/4.3.0/reference/connectors/gmail-connector/gmail-connector-overview/)
- [Gmail Example](https://mi.docs.wso2.com/en/4.3.0/reference/connectors/gmail-connector/gmail-connector-example/)
- [Gmail Reference](https://mi.docs.wso2.com/en/4.3.0/reference/connectors/gmail-connector/gmail-connector-config/)
- [Gmail Configuration](https://mi.docs.wso2.com/en/4.3.0/reference/connectors/gmail-connector/configuring-gmail-api/)

Therefore, closing the issue.
