### ISSUE TITLE
[msdynamics365] Need to create the Git documentation

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#710]
Moving the issue from https://github.com/wso2-extensions/esb-connector-msdynamics365/issues/7

![image](https://github.com/user-attachments/assets/f8fd29ce-9d35-4358-a22e-854266914939)

**Comment by arunans23** [comment]
This connector has not been tested with MI yet. This is hidden from Connector store. When we add back the connector to the connector store, we will add the connector with the proper docs.
