### ISSUE TITLE
[outlookmail] Need to create GitHub documentation

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#711]
Moving the issue https://github.com/wso2-extensions/esb-connector-outlookmail/issues/14

![image](https://github.com/user-attachments/assets/f37f4272-c9b1-4231-bd41-e46e70047a13)

**Comment by arunans23** [comment]
This connector has not been tested with MI yet. This is hidden from Connector store. When we add back the connector to the connector store, we will add the connector with the proper docs.
