### ISSUE TITLE
Add the updated mediator to the image in the "Command Message" document.

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/docs-mi#731]
## Description
This example now uses `Call` mediator instead of the `Callout` mediator. Therefor the respective image need to be updated

**Comment by DinithiDiaz** [comment]
Closing this as fixed. The updated page is available [here](https://mi.docs.wso2.com/en/latest/learn/enterprise-integration-patterns/message-construction/command-message/).
