### ISSUE TITLE
Image in the "Content Enricher" Doc need to be updated

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/docs-mi#746]
## Description
The indicated places of the below image need to be updated according to the updated approach. In the updated approach, a local entry is created but it is not saved as a registry resource. Therefore, mentioning `Governance Registry` can be omitted. Also the term `WSO2 ESB` need to be updated. 
<img width="728" alt="Screenshot 2024-08-14 at 13 29 51" src="https://github.com/user-attachments/assets/ef051e31-a76f-434c-8e4d-a4c39cab2bda">

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Fixed via https://github.com/wso2/docs-mi/pull/806/files.
