### ISSUE TITLE
Image in Publish-Subscribe Channel EIP needs to be updated. 

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/docs-mi#769]
## Description
> Since the Event Mediator is deprecated, the Publish-Subscribe Channel EIP sample scenario has been rewritten using an ActiveMQ JMS topic. Therefore, the image needs to be updated.
https://mi.docs.wso2.com/en/latest/assets/img/learn/enterprise-integration-patterns/messaging-channels/publish-subscribe-channel.png

**Comment by DinithiDiaz** [comment]
Added via https://github.com/wso2/docs-mi/pull/806.
