### ISSUE TITLE
[Amazon SQS ] Need to create Github documentation #11

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#770]
Moving the issue from https://github.com/wso2-extensions/esb-inbound-amazonsqs/issues/11

![image](https://github.com/user-attachments/assets/dea05dea-0e99-4b24-b541-4815aebf8f14)

**Comment by arunans23** [comment]
We have the relevant docs in https://mi.docs.wso2.com/en/latest/reference/connectors/amazonsqs-connector/amazonsqs-inbound-endpoint-reference-configuration/
