### ISSUE TITLE
Update helm resources git urls

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#771]
## Description
This task is to update helm resources git urls in the doc [1]. Currently it is pointing to v4.3.0 which is not available at the moment. Once the helm resources are properly configured, the doc has to be updated.

[1] https://mi.docs.wso2.com/en/latest/install-and-setup/setup/deployment/deploying-micro-integrator-with-helm/
## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
This will be tracked via https://github.com/wso2/docs-mi/issues/841. Therefore, closing this issue.
