### ISSUE TITLE
Update the image in the Event Message EIP

### ISSUE THREAD

**Issue by poorna2152** [wso2/docs-mi#773]
## Description
The image in the Event Message EIP needs to be updated to illustrate the new integration. This uses an integration which include JMS. And is similar to publisher subscriber EIP 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Updated via https://github.com/wso2/docs-mi/pull/813.
