### ISSUE TITLE
Channel Purger EIP Documentation Removed; To Be Added Later After Support Is Implemented

### ISSUE THREAD

**Issue by KalinduGandara** [wso2/docs-mi#779]
## Description
> The Channel Purger EIP documentation page was removed because MI currently lacks support for deleting messages from the message store. Once this support is implemented, the documentation will need to be updated and re-added. Here is the created issue: https://github.com/wso2/micro-integrator/issues/3511

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by chanikag** [comment]
We will add doc once the feature is available.
