### ISSUE TITLE
Update image in "Event Driven Consumer" Doc

### ISSUE THREAD

**Issue by chathuranga-jayanath-99** [wso2/docs-mi#784]
## Description
As per the update of this example, this image should contain the below changes. 

- `Event mediator` should be changed to `Message Processor`
- The term `Topic Subscriber` should be changed to `Simple Stock Quote Service`

![Screenshot 2024-08-16 at 16 18 09](https://github.com/user-attachments/assets/fa3dbdce-7441-44f5-a0ce-259e6e3ac158)

## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Updated via https://github.com/wso2/docs-mi/pull/811.
