### ISSUE TITLE
[SNMP]Need to create Github documentation

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#786]
Moving the issue from https://github.com/wso2-extensions/esb-connector-snmp/issues/12

![image](https://github.com/user-attachments/assets/524e8447-b801-4312-8b8d-57993d3eebe9)

**Comment by arunans23** [comment]
We have docs in the doc space https://mi.docs.wso2.com/en/latest/reference/connectors/smpp-connector/smpp-connector-overview/
