### ISSUE TITLE
[SMPP] Need to create the github documentation 

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#787]
Moving the issue from https://github.com/wso2-extensions/esb-connector-smpp/issues/14

![image](https://github.com/user-attachments/assets/ba3acfd3-0b7c-43df-b608-d3023b53ddc1)

**Description:**
SMPP connector doc are still in the confluence. Need to create the github docs and and add sample responses for each method.

**Comment by arunans23** [comment]
We have docs in the doc space. https://mi.docs.wso2.com/en/latest/reference/connectors/smpp-connector/smpp-connector-overview/
