### ISSUE TITLE
[Twitter] Need to create the github documentation

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#788]
Moving the issue from https://github.com/wso2-extensions/esb-connector-twitter/issues/21

![image](https://github.com/user-attachments/assets/11266971-01c6-4849-8780-493006710e9d)

**Comment by arunans23** [comment]
We have docs in the docs space. https://mi.docs.wso2.com/en/latest/reference/connectors/twitter-connector/twitter-connector-overview/
