### ISSUE TITLE
[File Connector] Update file connector document to version 2.0.22

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#789]
Moving the issue from https://github.com/wso2-extensions/esb-connector-file/issues/110

![image](https://github.com/user-attachments/assets/29ef7253-28e1-412e-8975-564c336833b6)

**Description:**
With file connector 2.0.22, in **file create** operation parameter ``source`` has changed to ``filePath``.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by arunans23** [comment]
We have docs in the docs space. https://mi.docs.wso2.com/en/latest/reference/connectors/file-connector/file-connector-overview/
