### ISSUE TITLE
Incorrect formatting in Starting the integration control plane page

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#792]
$subject in https://mi.docs.wso2.com/en/latest/install-and-setup/install/running-the-integration-control-plane/#starting-the-integration-control-plane

<img width="1011" alt="image" src="https://github.com/user-attachments/assets/a027b9de-f7af-4e04-95d3-53980148f988">

**Comment by DinithiDiaz** [comment]
Closing as fixed via https://github.com/wso2/docs-mi/pull/831/commits/adc0a331bd4904d71463bbb1240082b677f2b56c.
