### ISSUE TITLE
Incorrect link and instructions to download ICP

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#793]
$subject in 

https://mi.docs.wso2.com/en/latest/install-and-setup/install/installing-integration-control-plane/#installing-the-integration-control-plane_1
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/5accbfb1-8168-4e9a-92a4-6470e6a4d2e1">

**Comment by DinithiDiaz** [comment]
Closing as fixed via https://github.com/wso2/docs-mi/pull/831.
