### ISSUE TITLE
Outdated diagram in Develop Your First Integration page

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#795]
$subject in https://mi.docs.wso2.com/en/latest/get-started/development-kickstart/

The current image in the docs is the following. There are many similar follow up images with the same issue. So fix all

<img width="1148" alt="image" src="https://github.com/user-attachments/assets/287a4b3c-6098-4b44-8c34-00700fd1a871">

But the actual image should be 

<img width="1498" alt="image" src="https://github.com/user-attachments/assets/dc06544a-6089-4142-8015-5e64d9f52ed3">

**Comment by chanikag** [comment]
With the PR https://github.com/wso2/docs-mi/pull/1020 this doc is removed, as the step-by-step guide is available in quick start guide.
