### ISSUE TITLE
Integration Studio name is used in Develop Your First Integration page

### ISSUE THREAD

**Issue by anupama-pathirage** [wso2/docs-mi#798]
$subject in https://mi.docs.wso2.com/en/latest/get-started/development-kickstart/#invoke-the-healthcare-service

Question : Do we need to use Postman here, as this is a simple GET request? @chanikag 

Then if we need postman need to update the collection name in the step b of option 1. Also need to update the video. 

<img width="837" alt="image" src="https://github.com/user-attachments/assets/4b2e4f3d-8870-4654-b7d7-ba879e57fab1">

**Comment by chanikag** [comment]
Yes we can have only one option here. https://github.com/wso2/docs-mi/pull/912
