### ISSUE TITLE
activeMQ 18.5.x JMS 2.0

### ISSUE THREAD

**Issue by Boontjes** [wso2/docs-mi#832]
## Description
> A brief description of the improvement.
Apache ActiveMQ Classic 5.18.0 was released on Mar 24th, 2023. It’s a major milestone for the ActiveMQ Classic. ActiveMQ Classic 5.18.x brings:

It brings initial JMS 2.0 (javax.jms API namespace) and Jakarta Messaging 3.1 (jakarta.jms API namespace) client support. See the [JMS 2.0 page](https://activemq.apache.org/jms2) for more details on the available functionality and how to use the Jakarta Messaging support.
## Describe the problem(s)
> A detailed description of the purpose of this improvement.

## Describe your solution(s)
> A detailed description of how this improvement will solve the problem described above.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by Boontjes** [comment]
see here the Release info of ActiveMQ Classic 5.18.0: https://activemq.apache.org/components/classic/download/classic-05-18-00

**Comment by DinithiDiaz** [comment]
Reopening this since the changes need to be added to the versioning branch (4.2.0). Without these updates, the changes will not be reflected in the production documentation. @chanikag, please note.

**Comment by DinithiDiaz** [comment]
Hi @Boontjes, 

The [Connecting to ActiveMQ](https://mi.docs.wso2.com/en/4.3.0/install-and-setup/setup/brokers/configure-with-activemq/) is now updated.

Thank you for your contribution! We value your effort and appreciate your help in improving the documentation.
