### ISSUE TITLE
List of mediators are not directing to the correct pages

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#837]
## Description
https://mi.docs.wso2.com/en/latest/reference/mediators/about-mediators/#list-of-mediators

1. Some of the mediators are not redirecting to the correct mediator pages
2. [Binder](https://mi.docs.wso2.com/en/4.3.0/reference/mediators/builder-mediator) -> [Builder](https://mi.docs.wso2.com/en/4.3.0/reference/mediators/builder-mediator)
3. Some of the mediators are not listed: Data Service Call, NTLM, 

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Closing as fixed.
