### ISSUE TITLE
Update Documentation Links in Connector Store 

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#853]
## Description
Links to the documentation for [EI connectors](https://store.wso2.com/store/assets/esbconnector/list) in the Connector Store need to be updated.

- Some links lead to the APIM documentation and give 404 not found pages. (For example: [File Connector](https://store.wso2.com/store/assets/esbconnector/details/345e5336-0d1a-4fb9-93ec-dffee961804b), [Email Connector](https://store.wso2.com/store/assets/esbconnector/details/1de2b2ec-1fbd-4ca5-951e-9ff709ed0e59))

- Some of the links lead to the Confluence homepage. (For example: [Magento](https://store.wso2.com/store/assets/esbconnector/details/046bfb35-4b63-4bc9-b8ae-ab91f93af144), [DocuSign](https://store.wso2.com/store/assets/esbconnector/details/335702ff-8e66-4a57-9e0a-b189aa4c50d2))

## Describe your task(s)
The documentation link in meta.json file in each connector has to be updated
https://github.com/wso2-extensions/esb-connector-file/blob/master/.connector-store/meta.json#L5

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
I have added redirects to the APIM doc space (4.3.0 and master branches) via the following PRs:

- https://github.com/wso2/docs-apim/pull/7957
- https://github.com/wso2/docs-apim/pull/7956

Therefore, the APIM doc URLs containing the `latest` and `4.3.0` tags are redirected to the latest MI doc space.

**Comment by chanikag** [comment]
This is now fixed for the connectors displayed in the connector store.
