### ISSUE TITLE
Issues when connecting to non-public schemas in postgreSQL

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#857]
## Description
When trying out OData service in MI-4.1.0 with PostgreSQL, the following issue is occurred, when accessing tables outside of the public schema. There are no issues when try to access tables within the public schema.

```
Caused by: org.postgresql.util.PSQLException: ERROR: relation "salesforce_account" does not exist
Posição: 22
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
```

After a brief research on this, it was identified that PostgreSQL will look for the table in the public schema unless explicitly told otherwise. To access other schemas, we have to specify the schema name in the connection URL as follows [1],

postgres://user:password@host/dbname?sslmode=disable&search_path=schema 
Or set the DB schema directly from the DB as instructed in [2].

We need to add a note on the above information as currently this information is not specified in the documentation [3].

[1] https://stackoverflow.com/questions/4168689/is-it-possible-to-specify-the-schema-when-connecting-to-postgres-with-jdbc
[2] https://medium.com/@pulasthi7/configuring-wso2-products-to-use-custom-postgresql-schema-42c44c546a5c
[3] https://mi.docs.wso2.com/en/latest/learn/examples/data-integration/odata-service/

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
I have updated the following pages with the above info:

- [Setting up a PostgreSQL Database - Micro Integrator Documentation v4.3.0](https://mi.docs.wso2.com/en/latest/install-and-setup/setup/databases/setting-up-postgresql/)
- [Setting up a PostgreSQL Database - Micro Integrator Documentation v4.2.0](https://mi.docs.wso2.com/en/4.2.0/install-and-setup/setup/databases/setting-up-postgresql/)
- [Setting up a PostgreSQL Database - API Manager Documentation v4.2.0](https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/mi-setup/databases/setting-up-postgresql/#!)
- [Setting up a PostgreSQL Database - API Manager Documentation v4.1.0](https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/mi-setup/databases/setting-up-postgresql/)
