### ISSUE TITLE
Fix doc issues in SalesforceRest connector and inbound endpoint example pages

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#862]
## Description

1. Now the inbound endpoint is added as a separate component in the new connector store. This has to be reflected in the documentation.
(https://mi.docs.wso2.com/en/latest/reference/connectors/salesforce-connectors/sf-inbound-endpoint-example/#deployment)

2. In the documentation it is suggested that org.apache.synapse.salesforce.poll.class.jar file should be placed in lib folder (not working) , instead of need to be put in the dropping folder (working)

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by chanikag** [comment]
@gabilang Could you please comment on the second issue.Did you come across the same issue when you are testing the inbound endpoint.

**Comment by gabilang** [comment]
> @gabilang Could you please comment on the second issue.Did you come across the same issue when you are testing the inbound endpoint.

It needs to be added to the `<MI_HOME>/lib` folder and during the deployment it will be copied to the `<MI_HOME>/dropins` folder.

**Comment by chanikag** [comment]
1st issue is resolved with https://github.com/wso2/docs-mi/pull/1033
