### ISSUE TITLE
Publish unacked messages to Dead Letter Exchange

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#866]
## Description
We have been checking the documentation at[1] and it seems we have missed to add the parameter for the error exchange name.
dlq.exchange[2]
Dead letter exchange is not working and it seems it is, as you can check at this class[3] we need this value to enter to the requested flow.
Could you please check that and change the doc?

[1] https://apim.docs.wso2.com/en/4.1.0/integrate/examples/rabbitmq_examples/move-msgs-to-dlq-rabbitmq/#synapse-configurations

[2] https://medium.com/@philippbruegger/rabbitmq-requeue-delay-solution-with-wso2-b3e78af050ea

[3] https://github.com/wso2/wso2-axis2-transports/blob/v2.0.0-wso2v67/modules/rabbitmq/src/main/java/org/apache/axis2/transport/rabbitmq/ServiceTaskManager.java

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by GDLMadushanka** [comment]
Couldn't get this working with even after adding the following parameters (Rabbitmq version 4.0.3)
```
<parameter name="rabbitmq.message.error.exchange.name">orders-error-exchange</parameter>
<parameter name="rabbitmq.message.max.dead.lettered.count">5</parameter>
```

**Comment by GDLMadushanka** [comment]
need to revisit this doc issue after fixing the product issue https://github.com/wso2/product-micro-integrator/issues/3777
