### ISSUE TITLE
 Improve the EI documentation on how to configure secured proxy services

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#878]
## Description
How to configure secure proxy services is not mentioned in the Working with Proxy Servers section of the official documentation [1]. Anyway this has been documented here [2].

Wouldn’t it be better to add a reference here [1] as well, to avoid the confusions ?

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/configuring_proxy_servers/
[2] https://apim.docs.wso2.com/en/latest/reference/config-catalog-mi/#http-secured-proxy-profile:~:text=secured%20proxy%20profile-,%C2%B6,-%5B%5Btransport.http.secured_proxy_profile

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
This is available in the [MI documentation](https://mi.docs.wso2.com/en/4.3.0/reference/config-catalog-mi/#http-secured-proxy-profile). We need to add this to the EI documentation.

**Comment by rosensilva** [comment]
Do we still maintain EI Documentation?

**Comment by chanikag** [comment]
No, if this is there in MI docs, we can close this.
