### ISSUE TITLE
Format - Migration docs

### ISSUE THREAD

**Issue by chanikag** [wso2/docs-mi#881]
## Description
Currently the migration docs in [1], are not formatted.

[1] https://github.com/wso2-enterprise/migration-docs/tree/main/enterprise-integrator/migration-docs

## Describe your task(s)
> A detailed description of the task.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by DinithiDiaz** [comment]
Please find the progress of the task in [this sheet](https://docs.google.com/spreadsheets/d/1-4dC5sRCGNYKCsEjtfiAHi0pkdMn95-RyEODMxxxYws/edit#).

**Comment by DinithiDiaz** [comment]
MI/EI migration docs are available in the following locations:

- [Migration docs for MI v4.3.0 and later](https://github.com/wso2-enterprise/migration-docs/tree/main/micro-integrator/migration-docs/mi-4.3.0)
- [Migration docs for the earlier MI versions](https://github.com/wso2-enterprise/migration-docs/tree/main/api-manager/migration-docs/apim)
- [EI Migration docs](https://github.com/wso2-enterprise/migration-docs/tree/main/enterprise-integrator/migration-docs)

See the lists of formatted and unformatted migration docs [here](https://docs.google.com/spreadsheets/d/1-4dC5sRCGNYKCsEjtfiAHi0pkdMn95-RyEODMxxxYws/edit?gid=0#gid=0).

The rest of the migration docs will be formatted on demand. Hence closing this issue.
