### ISSUE TITLE
Invalid sample and description for rates-based policy use case in Throttle Mediator

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/docs-mi#889]
## Description
> A brief description of the bug.

The example given for the rates-based policy use case [1] is not working. There are some missing configurations in the sample. Also, the corresponding description is not valid for rates-based policy. 

[1] - https://mi.docs.wso2.com/en/4.2.0/reference/mediators/throttle-mediator/#example-for-a-rates-based-policy

## Steps to reproduce
> The steps to be followed to reproduce the issue.

## Affected version(s)
> The versions that are affected by the issue.

## Related issue(s) (optional)
> Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 

## Suggested label(s) (optional)
> Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.

## Suggested assignee(s) (optional)
> Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.

**Comment by malakaganga** [comment]
This is fixed in 4.3.0
