### ISSUE TITLE
Missing description of the "aggregateElementType" attribute in the "onComplete" element of an "aggregate" mediator.

### ISSUE THREAD

**Issue by gspadotto** [wso2/docs-mi#923]
**Description:**
There is no description for the "aggregateElementType" attribute in the "onComplete" element of an "aggregate" mediator.

**Suggested Labels:**
bug, micro-integrator

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Write a mediation sequence with an "aggregate" mediator. See the properties of that mediator in the graphical editor.

**Related Issues:**

**Comment by chanikag** [comment]
Will be done by https://github.com/wso2/docs-mi/issues/935

**Comment by gspadotto** [comment]
Hi @chanikag #935 has been closed but I still don't see the description of the "aggregateElementType" attribute. 
Am I missing something? 
Thanks

**Comment by chanikag** [comment]
Yes, we have reopend this.
