### ISSUE TITLE
Formatting issues in MongoDB connector reference document

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-mi#941]
## Description

Formatting issues can be observed in MongoDB connector reference document[1]

[1] - https://mi.docs.wso2.com/en/latest/reference/connectors/mongodb-connector/mongodb-connector-config/#operations

**Comment by DinithiDiaz** [comment]
This issue is tracked in https://github.com/wso2/docs-mi/issues/51 and the fixes are already sent in https://github.com/wso2/docs-mi/pull/929. Therefore closing this issue.
