### ISSUE TITLE
Improve code copy experience where switch cases are described

### ISSUE THREAD

**Issue by KCSAbeywickrama** [wso2/docs-mi#950]
## Description
> 
![image](https://github.com/user-attachments/assets/ebd0a718-9b30-482a-93f8-5338f1927eba)

In [this tutorial](https://mi.docs.wso2.com/en/latest/learn/integration-tutorials/routing-requests-based-on-message-content/) section where the switch cases are described, I noticed that when using the "copy" button, it copies the entire text, including the label "Case 1:". However, the expected behavior should be to copy only the value "grand oak community hospital" without the "Case 1:" part

![image](https://github.com/user-attachments/assets/660aa72e-10a0-4247-b4f3-9a8ec4a86517)
This is from step 10. Seems like when creating this project mistakenly "Case x:" parts have been included in Regex expressions.

## Suggestion

1. Remove the "Case 1:" part from the copyable code box, and instead, mention the case label separately. This will ensure only the necessary value is copied when using the "copy" button.
2. Update the SS with correctly working project in Step 10, 13, 19

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/docs-mi/pull/955
