### ISSUE TITLE
Ordering issue in steps in "Route Requests based on Message Content" tutorial

### ISSUE THREAD

**Issue by KCSAbeywickrama** [wso2/docs-mi#952]
## Description
> Step 15 should be under Step 11 as a sub-step in [this tutorial](https://mi.docs.wso2.com/en/latest/learn/integration-tutorials/routing-requests-based-on-message-content/)

## Side improvement suggestion
>In Step 17, instead of saying "Make sure to **name** the two Log mediators", it would be better to say something like "Make sure to **add description** for the two Log mediators" because the log mediator does not support a name field, it only supports a description.

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2/docs-mi/pull/955
