### ISSUE TITLE
Updating Instructions for Integrating WSO2 MI with Oracle WebLogic Server

### ISSUE THREAD

**Issue by sajith-madhusanka** [wso2/docs-mi#961]
## Description
As per the documentation [1], when configuring the WebLogic server with WSO2 Micro Integrator, it instruct to build the Web Logic client jar retrieved from the WebLogic server product distribution as OSGI bundle using the provided pom.xml file. But the link provided to download the pom.xml file seems to be broken and we have to follow the below steps to complete setup.

Since we couldn't find the pom.xml file mentioned in the documentation [1] (the provided SVN link is not reachable [2]), we created a pom.xml file to wrap the WebLogic client as an OSGI bundle, which prevents exporting the` javax.jms` and `javax.xml.namespace` packages. Please find the attached Maven project ([WebLogicClientWrapper.zip](https://github.com/user-attachments/files/17126089/WebLogicClientWrapper.zip)). 

Next, we have to deploy the `glassfish-corba-internal-api-4.2.5.jar` file to the `MI_HOME/wso2/lib` directory to resolve the CNF error related to the `org.omg.CORBA.MARSHAL` package after deploying the built wlfullclient.jar OSGI module to the MI_HOME/dropins directory. This issue arises because the relevant packages have been removed from the JDK 11 onwards; we need to explicitly add this JAR file to the classpath. 

Based on our investigations, the documentation should be updated as follows:

- Fix the broken link to the pom.xml file.
- Add instructions for building the OSGI bundle.
  -  Build the wlfullclient.jar file by executing the following command inside the `WEBLOGIC_HOME/wlserver_XX/server/lib` directory.
    ```
     java -jar wljarbuilder.jar -profile wlfullclient
    ```
   - Copy the built JAR file to the `<MAVEN_PROJECT_HOME>/lib` directory.
    - Execute the following command inside the `<MAVEN_PROJECT_HOME>` directory to build the OSGI bundle:
    ```
     mvn clean install
   ```
- Add instructions for placing the glassfish-corba-internal-api-4.2.5.jar file inside the MI_HOME/wso2/lib directory. 

## Steps to reproduce
Follow the Instructions for "Starting WebLogic and WSO2 Micro Integrator" as Provided in the Documentation [1]

## Affected version(s)
4.2.0

[1] https://mi.docs.wso2.com/en/4.2.0/install-and-setup/setup/brokers/configure-with-weblogic/#starting-weblogic-and-wso2-micro-integrator
[2] https://svn.wso2.org/repos/wso2/scratch/lasantha/weblogic-wrapper/pom.xml

**Comment by sajith-madhusanka** [comment]
Hi @chanikag @DinithiDiaz @IsuruMaduranga 

Based on the internal discussion [1], the supported WebLogic Server version should be updated to 14.1.1.0. The setup instructions should be updated as follows (Starting WebLogic and WSO2 Micro Integrator [3]):

- Install WebLogic 14.1.1.0 using the generic installer [2].
- Install Oracle JDK 11.
- Copy **wlthint3client.jar** from the **WL_HOME/server/lib/** directory to the **<MI_HOME>/lib/** directory.

Please ignore the previously shared steps.

[1] https://github.com/wso2-enterprise/wso2-mi-internal/issues/1077#issuecomment-2396549445
[2] https://www.oracle.com/middleware/technologies/weblogic-server-installers-downloads.html
[3] https://mi.docs.wso2.com/en/4.2.0/install-and-setup/setup/brokers/configure-with-weblogic/#starting-weblogic-and-wso2-micro-integrator

Thanks & Regards
Sajith M

**Comment by IsuruMaduranga** [comment]
Hi @sajith-madhusanka,

Weblogic download link[1] is blocked by WSO2 URL filter. Looks like a cert issue. If you have a downloaded pack please share it with me.

[1] https://download.oracle.com/otn/nt/middleware/14c/14110/fmw_14.1.1.0.0_wls_lite_Disk1_1of1.zip

Thanks,
Isuru

**Comment by DinithiDiaz** [comment]
The following pages have been updated.

https://mi.docs.wso2.com/en/latest/install-and-setup/setup/brokers/configure-with-weblogic/

**Comment by DinithiDiaz** [comment]
The following pages have been updated via the above PRs:

- https://mi.docs.wso2.com/en/latest/install-and-setup/setup/brokers/configure-with-weblogic/
- https://mi.docs.wso2.com/en/4.2.0/install-and-setup/setup/brokers/configure-with-weblogic/
- https://apim.docs.wso2.com/en/4.1.0/install-and-setup/setup/mi-setup/brokers/configure-with-weblogic/

Therefore, closing the issue.
