### ISSUE TITLE
HTTP log rotation configuration missed in EI 6.5.0 documentation

### ISSUE THREAD

**Issue by shefandarren** [wso2/docs-mi#981]
**Description:**
Access log rotation is disabled by default due to various requirements. But we can enable log rotation by adding the nhttp.is.log.rotatable=true property to the nhttp.properties file located under <EI_HOME>/conf directory.

The documentation in [1] must be updated with this information. 

**Suggested Labels:**
Docs

**Affected Product Version:** 6.5.0

[1] https://docs.wso2.com/display/EI650/Monitoring+Access+Logs

**Comment by SanojPunchihewa** [comment]
This access log configuration is outdated now via https://github.com/wso2/micro-integrator/issues/3281. We use log4j for access logs as well. Hence we need to fine tune the related log4j appender for log rotation. @arunans23 Have we updated the MI docs with log4j configs for access logs?

**Comment by arunans23** [comment]
In the new version of MI 4.3.0, access logs are logged using log4j2 configuration. Hence we do not such parameters in the access-log.properties file anymore. Updated PR. https://github.com/wso2/docs-mi/pull/1125

**Comment by arunans23** [comment]
Resolved with https://github.com/wso2/docs-mi/pull/1125
