### ISSUE TITLE
Incorrect build and run steps

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-mi#986]
## Description

The [Send a Simple Message to a Service](https://mi.docs.wso2.com/en/latest/learn/integration-tutorials/sending-a-simple-message-to-a-service/#step-3-build-and-run-the-artifacts) documentation mention we can use the command `MI: Build and Run` to build and run a integration project. However in MI VSCode 1.1.0 plugin, there is no such command.

**Comment by chanikag** [comment]
PR https://github.com/wso2/docs-mi/pull/990
