### ISSUE TITLE
Diagram alignment issue in Deploying Artifacts page

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/docs-mi#987]
## Description

$subject on https://mi.docs.wso2.com/en/latest/develop/deploy-artifacts/

![Screenshot 2024-10-01 at 08 56 24](https://github.com/user-attachments/assets/4f09dfb2-5e7b-494a-b3d9-8121e77edfc3)

**Comment by DinithiDiaz** [comment]
I'm using 1512x982 and 1920x1080 resolutions, and the images render fine. However, when I switch to a higher resolution (2048x1330), I could experience this behavior.

**Comment by DinithiDiaz** [comment]
Verified the fixes. Therefore closing the issue.
